### ISSUE TITLE
python "118. Pascal's Triangle" error

### ISSUE THREAD

**Issue by 625781186** [apachecn/awesome-algorithm#143]
118. Pascal's Triangle
![image](https://user-images.githubusercontent.com/30521429/48840647-37ca9480-edca-11e8-8358-5c8f3ad706cb.png)

**Comment by Lisanaaa** [comment]
This solution is acceptable for Python2.7, if you want to use Python3, you can see the latest solution in https://github.com/apachecn/awesome-algorithm/blob/master/docs/Leetcode_Solutions/Python/118._pascal's_triangle.md
