### ISSUE TITLE
Duplicate file issue

### ISSUE THREAD

**Issue by MarsXue** [apachecn/awesome-algorithm#194]
Hey there,

I believe that there are two files with the same name, which causes the issue that one is trying to  replace the other, so git keeps asking me to commit this modification. I can not do anything like stash or checkout to avoid it. Please delete either file.

Path: docs/Leetcode_Solutions/C++/024._Swap_Nodes_in_Pairs.md

**Comment by Lisanaaa** [comment]
fixed, thank you.
