### ISSUE TITLE
Leetcode 33 solution in python implementation lacks picture

### ISSUE THREAD

**Issue by taoweicn** [apachecn/awesome-algorithm#79]
The picture in [this solution](https://github.com/apachecn/awesome-algorithm/blob/master/docs/Leetcode_Solutions/Python/033._search_in_rotated_sorted_array.md) was not found.

**Comment by Lisanaaa** [comment]
I can see it right there, you may check your internet again.

**Comment by Lisanaaa** [comment]
Thank you very much for pointing out this, just fix it up.
